services:
  plutus-mongodb:
    image: mongo:latest
    container_name: plutus-mongodb
    volumes:
      - mongodb_data_container:/data/db
      - ./docker-entrypoint-initdb.d/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    environment:
      MONGO_INITDB_ROOT_USERNAME: "root"
      MONGO_INITDB_ROOT_PASSWORD: "rootpassword"
      MONGO_INITDB_DATABASE: "plutus"
    ports:
      - "27017:27017"
    networks:
      - plutus_network

  plutus:
    build:
      context: .
    environment:
      SERVER_HOST: '0.0.0.0'
      SERVER_PORT: 8000
      LOG_LEVEL: 10
      CORS_ALLOWED_ORIGINS: "http://localhost:80,http://localhost:8080,http://localhost:4000"
      MONGODB_CONNECTION_STRING: "mongodb://root:rootpassword@plutus-mongodb:27017"
      MONGODB_DATABASE: "plutus"
      ROOT_PATH: "/api/v1/plutus"
    ports:
      - "8000:8000"
    networks:
      - plutus_network

volumes:
  mongodb_data_container:
    name: "mongodb_data_container"

networks:
  plutus_network:
    driver: bridge
